### ISSUE TITLE
Hosting on Heroku

### ISSUE THREAD

**Issue by patrickw098** [patrickw098/Tritone#2]
- [ ]  Hosting on heroku
- [ ]  Verify user auth is bug free
- [ ]  Smooth navigation 
- [ ]  Demo User login
- [ ]  Logout feature
- [ ]  Correctly populates servers
- [ ]  Can create servers
- [ ]  Can search for and join servers that the user is not already a member of

**Comment by s-pangburn** [comment]
Hey Patrick! Please break up this issue into discrete issues for each MVP. It is much harder to get an idea of your progress when I end up lumping all your feedback into a single thread.

I will treat this issue as the Heroku Hosting MVP, which is now considered complete. Please open other issues for Auth, Servers, and any other features that may be finished!
