### ISSUE TITLE
User Auth Done

### ISSUE THREAD

**Issue by patrickw098** [patrickw098/Tritone#3]
- [x] Smooth, bug-free, navigation
- [x] Users can create an account and login with an exiting account
- [x] Users can demo login
- [x] Users can log out

**Comment by s-pangburn** [comment]
Thank you Patrick! Please stop and make these changes before continuing with your current MVP!

- [x] The initial screen looks kind of empty save the div and two buttons, and does not make a good first impression. I would recommend either [cloning the layout of the splash page from Discord exactly](https://discordapp.com/) or dropping this page and starting straight with a login dialog (if you do this, the demo login button would have to be moved to the form.)
- [x] When you click "Demo User Login" there is an additional step where you have to say "Open App". It is not clear why this is necessary, and an experienced programmer will assume your code is not robust and that you are working around something in an inelegant way.
- [x] Your `input::focus` border color is the same as your `input::hover` color in your SessionForm. This causes visual confusion, they should either be different shades or different colors entirely (Discord uses black for mouseover, for example)
- [x] Your errors can't display like this:
![screen shot 2018-06-07 at 1 18 39 pm](https://user-images.githubusercontent.com/8031316/41123987-5ccd65a8-6a55-11e8-915a-d27747e9e9bb.png)
  * They should be listed one after the other. It really is okay if the form shifts a little bit, so long as movement is only in the top or bottom half and the padding stays consistent.
- [x] The gear icon should not be your log out button. It isn't clear that it's supposed to log you out, so a person browsing your website could easily do so by accident (if this is just a temporary thing, you should finish it before moving on 🙂 )
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`, depending on your login status.
- [x] Bring the styling of your nav to be more in-line with the Discord splash page. Specifically, the logo sizing and login button should look nearly identical.
- [x] The "Login" in "Already have an account?" should be two words, I think. Just grammatically.
- [x] When I log in and return to the website, I should not have to click "Open App" to continue, it should just detect that I am logged in and redirect me to the main chat page.
